# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('salario', models.FloatField()),
                ('tipo_contrato', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('CLT', 'Consolidação das Leis do Trabalho')], max_length=50)),
                ('status', models.BooleanField(default=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Empresa')),
            ],
        ),
    ]
