# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_vaga', to='api.Vaga')),
            ],
        ),
    ]
